// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CaliburnMicro2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CaliburnMicro2));
        
        string IMigrationMetadata.Id
        {
            get { return "202006121738207_CaliburnMicro2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
